version: '2.4'

services:

  frontend:
    image: "grocy/frontend:v3.3.1"
    build:
      args:
        GROCY_VERSION: v3.3.1
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-frontend
    depends_on:
      - backend
    ports:
      - '${GROCY_HTTP_PORT}:8080'
      - '${GROCY_HTTPS_PORT}:8443'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx

  backend:
    image: "grocy/backend:v3.3.1"
    build:
      args:
        GROCY_VERSION: v3.3.1
        PLATFORM: linux/amd64
        COMPOSER_VERSION: "2.1.5"
        COMPOSER_CHECKSUM: "be95557cc36eeb82da0f4340a469bad56b57f742d2891892dcb2f8b0179790ec"
      context: .
      dockerfile: Containerfile-backend
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php8
      - ${GROCY_DATA_VOLUME}/data:/var/www/data
    dns:
      - ${GROCY_DNS1}
      - ${GROCY_DNS2}
